config/routes.rb
# == Route Map
#
#          Prefix Verb URI Pattern                Controller#Action
#      tags_index GET  /tags/index(.:format)      tags#index
#     tags_create GET  /tags/create(.:format)     tags#create
#        tags_new GET  /tags/new(.:format)        tags#new
#       tags_edit GET  /tags/edit(.:format)       tags#edit
#       tags_show GET  /tags/show(.:format)       tags#show
#     tags_update GET  /tags/update(.:format)     tags#update
#    tags_destroy GET  /tags/destroy(.:format)    tags#destroy
#   outfits_index GET  /outfits/index(.:format)   outfits#index
#  outfits_create GET  /outfits/create(.:format)  outfits#create
#     outfits_new GET  /outfits/new(.:format)     outfits#new
#    outfits_edit GET  /outfits/edit(.:format)    outfits#edit
#    outfits_show GET  /outfits/show(.:format)    outfits#show
#  outfits_update GET  /outfits/update(.:format)  outfits#update
# outfits_destroy GET  /outfits/destroy(.:format) outfits#destroy
#     users_index GET  /users/index(.:format)     users#index
#    users_create GET  /users/create(.:format)    users#create
#       users_new GET  /users/new(.:format)       users#new
#      users_edit GET  /users/edit(.:format)      users#edit
#      users_show GET  /users/show(.:format)      users#show
#    users_update GET  /users/update(.:format)    users#update
#   users_destroy GET  /users/destroy(.:format)   users#destroy
#            root GET  /                          pages#home
#

Rails.application.routes.draw do

  root :to => 'pages#home'

  get '/login' => 'session#new'
  post '/login' => 'session#create'
  get '/logout' => 'session#destroy'

  resources :tags
  resources :users
  resources :outfits

end

app/models/outfit.rb
# == Schema Information
#
# Table name: outfits
#
#  id          :integer          not null, primary key
#  title       :string
#  description :text
#  image       :text
#  user_id     :integer
#

class Outfit < ActiveRecord::Base
  belongs_to :user
  has_and_belongs_to_many :tags
end

app/models/tag.rb
# == Schema Information
#
# Table name: tags
#
#  id      :integer          not null, primary key
#  tag     :text
#  user_id :integer
#

class Tag < ActiveRecord::Base
  belongs_to :user
  has_and_belongs_to_many :outfits
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id         :integer          not null, primary key
#  name       :string
#  location   :string
#  picture    :text
#  created_at :datetime
#  updated_at :datetime
# has_secure_password set up within the class. add brcypt in gems. 

class User < ActiveRecord::Base
  has_many :outfits
  has_many :tags
  has_secure_password

  validates :name, :presence => true
  validates :name, :uniqueness => true

  validates :username, :presence => true
  validates :username, :uniqueness => true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :authenticate 

  private 
  def authenticate
    # session[user:id] = nil
    @current_user = User.find session[:user_id] if session[:user_id]
  end
end

app/controllers/outfits_controller.rb
class OutfitsController < ApplicationController
#executing ruby commands, controls behaviour

#list all the outfit
#current user all outfit
  def index
    if @current_user
      @outfit = @current_user.outfits
    else 
      @outfit = Outfit.all
    end
  end




  def new
    @outfit = Outfit.new
  end
  


  def create
    @outfit = @current_user.outfits.new outfit_params
    if @outfit.save                                    #if it saves/works
      redirect_to "/outfits/#{ @outfit.id }"           #show the individual page
    else
      render :new                                       #if not load form again
    end
  end

  def show
    @outfit = Outfit.find params[:id]
  end

  def edit
    @outfit = Outfit.find params[:id]
  end

  def update
    @outfit = Outfit.find params[:id]
    @outfit.update outfit_params

    redirect_to outfit_path( @outfit )
  end 

  def destroy
  end
end

  private    
  def outfit_params
    params.require(:outfit).permit(:title, :description, :image) 
  end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/session_controller.rb
class SessionController < ApplicationController
  def new
  end

  #creating a new session. has to match username = name in database. 
  #set up the session for the id of the user 
  def create
    user = User.find_by :username => params[:username]
    if user.present? && user.authenticate(params[:password]) 
      session[:user_id] = user.id
      redirect_to root_path
    else
      flash[:notice] = "Invalid login information, please try again."
      redirect_to login_path
    end
  end


  #destroys the session
  #redirect to home
  def destroy
    session[:user_id] = nil
    redirect_to root_path
  end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  def index
  end

  def create
  end

  def new
  end

  def edit
  end

  def show
  end

  def update
  end

  def destroy
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
 
# List all users on page
  def index
    @user = User.all 
  end


# Create new user 
# typing & displaying the information
# Where the user lands
  def new
    @user = User.new
  end
  

# Where it goes after the new form
# accepting the information
# Creates a new user with information as objects to go in the database.
  def create
    @user = User.new user_params #authenticating the user's information. fill in the db with these values.
    if @user.save                          #if it saves,
      redirect_to "/users/#{ @user.id }"   #redirect to their profile page
    else
      render :new                #if not new form.
    end
  end


# Shows an individual user by their unique ID (the information is then clarified in show.html.erb)
# refers to the current user (in the session that is declared in app_controller (current_user))
  def show
    @user = @current_user       
    @user = User.find( params[:id] ) 
  end


# SHOWS the edit form
# Using the current user information to edit BUT  
# Using the same skeleton (_form.html.erb), but different flesh ( which is current user defined by user)
  def edit
    @user = @current_user 
    # render :new 
  end


# SHOWS AND EDIT the user form
# takes in the info and INPUT into database
# redirect to home
  def update
    @current_user.update user_params
    redirect_to root_path
  end

  def destroy
    # Deletes the current user
    @current_user.destroy
    redirect_to root_path 
  end


#everything underneath here is private
#on the form, accept the required fields to be stored in db

  private    
  def user_params
    params.require(:user).permit(:name, :location, :picture, :username, :password, :password_confirmation)
  end


#redirect to root path unless the user is present AND the user is admin (both has to be true)
#execute admin features  
  def check_if_admin
    redirect_to root_path unless @current_user.present? && @current_user.admin?
  end
end

app/helpers/application_helper.rb
#this will appear through out the whole website
#intellinav - changes the view depending on user status
  # user admin - show all the users
  # user logged in - show log out / edit profile
  # user logged out / new user - show log in & new user sign up

module ApplicationHelper
  def intellinav
    nav = "<nav><a href='/''>#{ image_tag 'logo.svg', :class => 'svg' }</a><ul>"

    if @current_user.present?
      nav += '<li>' + link_to("#{ @current_user.name }", edit_user_path(@current_user)) + '</li>'      
      nav += '<li>' + link_to("New Outfit", new_outfit_path) + '</li>'
      nav += '<li>' + link_to("All my outfits", outfits_path) + '</li>'
      nav += '<li class="log_out">' + link_to("Log out", logout_path) + '</li>'
    else
      nav += '<li>' + link_to('Log in', login_path) + '</li>'
      nav += '<li class="sign_up">' + link_to('Sign up', new_user_path) + '</li>'
    end
    nav +='</ul></nav>'
    nav
  end
end




#keep home button
#input any if statements in here to not clutter the view page 

app/helpers/outfits_helper.rb
module OutfitsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/session_helper.rb
module SessionHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Wardrobe</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <script src="//cdnjs.cloudflare.com/ajax/libs/paper.js/0.9.22/paper-full.min.js"></script>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  
</head>
<body>

<%= image_tag( "background.svg", :class => "decor background-image" ) %>  

<canvas id="myCanvas" resize></canvas>

<%== intellinav  %>
<div class="container">
  <%= yield %>
</div>

  <%= javascript_include_tag 'chain.js', :type => "text/x-paperscript", :canvas => "myCanvas" %>
</body>
</html>

app/views/outfits/_form.html.erb
<%= form_for @outfit do |f| %>
<p>
  <%= f.label :title %>
  <%= f.text_field :title, :autofocus => true, :required => true %>
</p>

<br>

<p>
  <%= f.label :description %>
  <%= f.text_field :description %>
</p>

<br>

<p>
  <%= f.label :image %>
  <%= f.text_field :image, :required => true %>
</p>

<br>
  <%#= f.label :tag %>
  <%#= f.text_field :tag %>
  <%= f.submit %>
</p>

<% end %>

<div class="photo">
  <p>
    <% if @outfit.image %>
      <%= image_tag @outfit.image %>
    <% end %>
  </p>
</div>

app/views/outfits/_outfit.html.erb
<%= form_for @outfit do |f| %>
<p>
  <%= f.label :title %>
  <%= f.text_field :title, :autofocus => true, :required => true %>
</p>
<p>
  <%= f.label :description %>
  <%= f.text_field :description %>
</p>
<p>
  <%= f.label :image %>
  <%= f.text_field :image, :required => true %>
</p>
<p>
  <%#= f.label :tag %>
  <%#= f.text_field :tag %>
</p>
<p>
  <%= f.submit %>
</p>

<% end %>

app/views/outfits/destroy.html.erb
<h1>Outfits#destroy</h1>
<p>Find me in app/views/outfits/destroy.html.erb</p>

app/views/outfits/edit.html.erb
<h1>Edit my Outfit</h1>

<%= render "form" %>

app/views/outfits/index.html.erb
<div class="collection">
<h1>My Collection</h1>

  <br><br>
  <h4>Some looks I adore ...  </h4>
  <% @outfit.each do |outfit| %>
  <%= link_to(image_tag(outfit.image, :class => 'thumb', :title => outfit.title), outfit) %>
  <% end %>
</div>











<br><br><br><br>
  <div id="disqus_thread"></div>
<script type="text/javascript">
    /* * * CONFIGURATION VARIABLES * * */
    var disqus_shortname = 'amazing-wardrobe';
    
    /* * * DON'T EDIT BELOW THIS LINE * * */
    (function() {
        var dsq = document.createElement('script'); dsq.type = 'text/javascript'; dsq.async = true;
        dsq.src = '//' + disqus_shortname + '.disqus.com/embed.js';
        (document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0]).appendChild(dsq);
    })();
</script>
<noscript>Please enable JavaScript to view the <a href="https://disqus.com/?ref_noscript" rel="nofollow">comments powered by Disqus.</a></noscript>

app/views/outfits/new.html.erb
<div class="new-outfit">
<h1>Create New Outfit </h1>
<%= render "form" %>
</div>

app/views/outfits/show.html.erb
<div class="look">
<h1>The Look</h1>
<p> Title : <%= @outfit[:title] %> </p>
<p> About this outfit : <%= @outfit[:description] %> </p>
<p><%= image_tag @outfit.image , :class => 'regular' %></p>
<p><%=link_to("Edit this outfit", edit_outfit_path) %></p> 
</div>

<!-- could totally resize this image and make it bigger   -->

app/views/pages/home.html.erb
 <%# if @current_user %>
 <%#= render :partial => 'dashboard' %>
 <%# end %>

app/views/session/new.html.erb
<div class="new"> 
  <h1> LOG IN </h1>
  <% if (flash) %>
    <%= flash["notice"] %>
  <% end %>

  <%= form_tag '/login' do %>
    <p>
      <%= label_tag 'username' %>
      <%= text_field_tag 'username' %>
    </p>

    <p>
     <%= label_tag 'password' %> 
     <%= password_field_tag 'password' %>
    </p>

    <p>
      <%= submit_tag 'Login' %>
    </p>
    <% end %>
</div>




<!-- this is creating a new session for user. 
new users create account, and logs in again to be authenticated with session.

create users -> routed home -> log in with user params in db(created in new users) -> login complete -> stores username and password params for session id -> each time logged in, a unique session id is created. 
-->

app/views/tags/destroy.html.erb
<h1>Tags#destroy</h1>
<p>Find me in app/views/tags/destroy.html.erb</p>

app/views/tags/edit.html.erb
<h1>Tags#edit</h1>
<p>Find me in app/views/tags/edit.html.erb</p>

app/views/tags/index.html.erb
<h1>Tags#index</h1>
<p>Find me in app/views/tags/index.html.erb</p>

app/views/tags/new.html.erb
<h1>Tags#new</h1>
<p>Find me in app/views/tags/new.html.erb</p>

app/views/tags/show.html.erb
<h1>Tags#show</h1>
<p>Find me in app/views/tags/show.html.erb</p>

app/views/users/_form.html.erb
<!-- this is where the form skeleton be for users. 
used in edit and new -->

<%= form_for @user do |f| %>
<p>
  <%= f.label :username %>
  <%= f.text_field :username, :required => true %>
</p>
<p>
  <%= f.label :name %>
  <%= f.text_field :name, :autofocus => true, :required => true %>
</p>
<p>
  <%= f.label :password %>
  <%= f.password_field :password, :required => true %>
</p>
<p>
  <%= f.label :password_confirmation %>
  <%= f.password_field :password_confirmation, :required => true %>
</p>
<p>
 <%= f.label :location %> 
 <%= f.text_field :location %>
</p>
<p>
  <%= f.label :picture %>
  <%= f.text_field :picture %>
</p>

<p>
  <%= f.submit %>
</p>
<% end %>

<div class="photo">
  <p>
    <% if @user.picture %>
      <%= image_tag @user.picture %>
    <% end %>
  </p>
</div>

app/views/users/destroy.html.erb
<h1>Users#destroy</h1>
<p>Find me in app/views/users/destroy.html.erb</p>

app/views/users/edit.html.erb
<div class="edit">
  <h1> Edit my Profile </h1>
<%= render "form" %>

</div>

app/views/users/index.html.erb
<h1> all user list </h1>

app/views/users/new.html.erb
<h1> create new profile </h1>

<!-- - repeated skeleton
- what new users see 
- welcome message etc 
- create new user form goes here (_form.html.erb)
- intellinav goes in application helper (to not repeat) -->


<% if (@user.errors.any?) %>
  <ol>
    <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
  </ol>
<% end %>



<!-- for each new user repeat this step -->
<!-- is this how you show form  -->
<%= render "form" %> 

app/views/users/show.html.erb
<div class="show">
<h1> <%= @user[:name] %>  's profile </h1>

<p>Username : <%= @user[:username] %></p>
<p>Location : <%= @user[:location] %></p>
</div>
<p><%= image_tag @user.picture %></p>